### ISSUE TITLE
Error: Cannot run program "git" 

### ISSUE THREAD

**Issue by aperiooculus** [yoshiyoshifujii/gitbucket-commitgraphs-plugin#8]
I installed the most recent compiled jar today and I get the following stack trace when trying to view a Commit graph. I'm using gitbucket version 3.12 and commit-graphs v3.12

> java.io.IOException: Cannot run program "git" (in directory "C:\Windows\System32\config\systemprofile.gitbucket\repositories\eCommerce\StorefrontAnalytics.git"): CreateProcess error=2, The system cannot find the file specified
>   at java.lang.ProcessBuilder.start(Unknown Source)
>   at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
>   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:141)
>   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:109)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsControllerBase$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$2.apply(CommitGraphsController.scala:30)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsControllerBase$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$2.apply(CommitGraphsController.scala:28)
>   at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
>   at scala.collection.Iterator$class.toStream(Iterator.scala:1180)
>   at scala.collection.AbstractIterator.toStream(Iterator.scala:1194)
>   at scala.collection.TraversableOnce$class.toSeq(TraversableOnce.scala:296)
>   at scala.collection.AbstractIterator.toSeq(Iterator.scala:1194)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsControllerBase$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(CommitGraphsController.scala:41)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsControllerBase$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(CommitGraphsController.scala:27)
>   at gitbucket.core.util.ControlUtil$.using(ControlUtil.scala:24)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsControllerBase$$anonfun$1$$anonfun$apply$1.apply(CommitGraphsController.scala:27)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsControllerBase$$anonfun$1$$anonfun$apply$1.apply(CommitGraphsController.scala:23)
>   at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1$$anonfun$apply$12.apply(Authenticator.scala:123)
>   at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1$$anonfun$apply$12.apply(Authenticator.scala:121)
>   at scala.Option.map(Option.scala:146)
>   at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1.apply(Authenticator.scala:121)
>   at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1.apply(Authenticator.scala:120)
>   at gitbucket.core.util.ControlUtil$.defining(ControlUtil.scala:12)
>   at gitbucket.core.util.ReferrerAuthenticator$class.gitbucket$core$util$ReferrerAuthenticator$$authenticate(Authenticator.scala:120)
>   at gitbucket.core.util.ReferrerAuthenticator$class.referrersOnly(Authenticator.scala:115)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsController.referrersOnly(CommitGraphsController.scala:16)
>   at me.huzi.gitbucket.commitgraphs.controller.CommitGraphsControllerBase$$anonfun$1.apply(CommitGraphsController.scala:23)
>   at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:285)
>   at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
>   at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
>   at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:189)
>   at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
>   at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:278)
>   at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:27)
>   at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:88)
>   at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:82)
>   at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:189)
>   at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
>   at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
>   at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:27)
>   at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:253)
>   at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:251)
>   at scala.Option.flatMap(Option.scala:171)
>   at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:251)
>   at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:250)
>   at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
>   at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:250)
>   at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:27)
>   at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:175)
>   at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
>   at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
>   at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
>   at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
>   at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
>   at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
>   at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
>   at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
>   at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
>   at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
>   at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
>   at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
>   at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
>   at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
>   at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
>   at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
>   at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
>   at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
>   at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
>   at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
>   at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
>   at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
>   at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
>   at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
>   at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
>   at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
>   at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
>   at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:68)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>   at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:74)
>   at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
>   at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
>   at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:178)
>   at scala.Option.getOrElse(Option.scala:121)
>   at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:178)
>   at scala.Option.getOrElse(Option.scala:121)
>   at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:177)
>   at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
>   at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
>   at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
>   at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
>   at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
>   at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
>   at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
>   at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
>   at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
>   at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
>   at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
>   at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
>   at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
>   at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
>   at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
>   at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
>   at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
>   at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
>   at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
>   at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
>   at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
>   at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
>   at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
>   at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
>   at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
>   at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
>   at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
>   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
>   at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
>   at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:68)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>   at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:37)
>   at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:28)
>   at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
>   at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
>   at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
>   at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
>   at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
>   at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
>   at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
>   at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
>   at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:28)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
>   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
>   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
>   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
>   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
>   at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
>   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
>   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
>   at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
>   at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
>   at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2517)
>   at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2506)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>   at java.lang.Thread.run(Unknown Source)
> Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
>   at java.lang.ProcessImpl.create(Native Method)
>   at java.lang.ProcessImpl.<init>(Unknown Source)
>   at java.lang.ProcessImpl.start(Unknown Source)
>   ... 164 more

**Comment by aperiooculus** [comment]
Rebooting after installing git and updating the system path resolved this issue.
